### ISSUE TITLE
The "listener" argument must be of type function - incompatibility with `agent-base@v4`

### ISSUE THREAD

**Issue by gerbyzation** [mswjs/interceptors#143]
When setting up msw and the first route to mock I was encountering the following error
```js
const server = setupServer(
  rest.get(
    `${envConfig.API_URL}/api/admin/affiliates/:id`,
    (req, res, ctx) => {
      return res(
        ctx.text('lol')
        // ctx.json({
      );
    }
  )
);
  
server.listen({onUnhandledRequest: 'bypass'})
```
```
2021-07-20T16:02:43.384Z ERROR Master [Anonymous] TypeError [ERR_INVALID_ARG_TYPE] [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type function. Received an instance of Object
    at checkListener (events.js:111:11)
    at ClientRequest.once (events.js:435:3)
    at new ClientRequest (_http_client.js:194:10)
    at Object.request (https.js:314:10)
    at makeRequest (/Users/[redacted]/projects/[redacted]-src/node_modules/newrelic/lib/instrumentation/core/http.js:501:22)
    at instrumentRequest (/Users/[redacted]/projects/[redacted]-src/node_modules/newrelic/lib/instrumentation/core/http-outbound.js:130:21)
    at wrapped (/Users/[redacted]/projects/[redacted]-src/node_modules/newrelic/lib/transaction/tracer/index.js:198:22)
    at Tracer.addSegment (/Users/[redacted]/projects/[redacted]-src/node_modules/newrelic/lib/transaction/tracer/index.js:93:48)
    at instrumentOutbound (/Users/[redacted]/projects/[redacted]-src/node_modules/newrelic/lib/instrumentation/core/http-outbound.js:80:23)
    at Object.wrappedRequest (/Users/[redacted]/projects/[redacted]-src/node_modules/newrelic/lib/instrumentation/core/http.js:499:12)
    at Object.<anonymous> (/Users/[redacted]/projects/[redacted]-src/node_modules/agent-base/patch-core.js:25:22)
    at /Users/[redacted]/projects/[redacted]-src/node_modules/socks-proxy-agent/node_modules/agent-base/patch-core.js:23:20
    at Object.proxiedOriginalRequest (/Users/[redacted]/projects/[redacted]-src/node_modules/@mswjs/interceptors/src/interceptors/ClientRequest/index.ts:66:29)
    at ClientRequestOverride.<anonymous> (/Users/[redacted]/projects/[redacted]-src/node_modules/@mswjs/interceptors/src/interceptors/ClientRequest/createClientRequestOverride.ts:277:17)
    at step (/Users/[redacted]/projects/[redacted]-src/node_modules/@mswjs/interceptors/lib/interceptors/ClientRequest/createClientRequestOverride.js:33:23)
    at Object.next (/Users/[redacted]/projects/[redacted]-src/node_modules/@mswjs/interceptors/lib/interceptors/ClientRequest/createClientRequestOverride.js:14:53)
    at fulfilled (/Users/[redacted]/projects/[redacted]-src/node_modules/@mswjs/interceptors/lib/interceptors/ClientRequest/createClientRequestOverride.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
After a good while of painfull debugging I managed to narrow it down to the following call:
https://github.com/mswjs/interceptors/blob/ca859e5273c8949b95779e730167d70246cab912/src/interceptors/ClientRequest/createClientRequestOverride.ts#L277

The `pureMethod` in this scenario is this function from `agent-base`:
```js
https.request = (function(request) {
  return function(_options, cb) {
    let options;
    if (typeof _options === 'string') {
      options = url.parse(_options);
    } else {
      options = Object.assign({}, _options);
    }
    if (null == options.port) {
      options.port = 443;
    }
    options.secureEndpoint = true;
    return request.call(https, options, cb);
  };
})(https.request);
```
https://github.com/TooTallNate/node-agent-base/blob/7ea2dde4c21f2f5cfe071e99335d35b9c0a1403e/patch-core.js#L11-L25

`http.request` has the following signatures (`http.get` has an identical argument signature):
```
http.request(options[, callback])
http.request(url[, options][, callback])
```
This is the type of `pureMethod`, so it's expected to accept both request signatures: https://github.com/mswjs/interceptors/blob/ca859e5273c8949b95779e730167d70246cab912/src/interceptors/ClientRequest/createClientRequestOverride.ts#L25

As we can see `agent-base@v4` however only supports the first signature (`options[, callback]`) while the arguments given follow the second signature causing options to be passed as the callback which is the cause of the error.

![agent base error](https://user-images.githubusercontent.com/2500973/126815025-9f71367f-d251-4b1c-a3e1-f533d7bcb745.png)

I've managed to patch this issue for now by upgrading `agent-base` to version 6 via yarn resolutions as later versions don't monkey patch `http.request`

Not sure if this requires any action - as far as I know this was just another dependency interferring - but on @kettanaito request opening an issue so it can be evaluated if this needs any action and is here for the search results for the next poor soul who runs into this issue and otherwise has no relevant google hits 😄

**Comment by kettanaito** [comment]
Thanks for raising this, @gerbyzation. 

At first glance, it appears that adopting the `(options, callback)` signature for the `pureMethod` may be a good solution. I believe that the request URL can be parsed and represented in the `options` using the properties like `hostname` etc. 

On the other hand, I remember past regressions due to the call signature of `pureMethod` that resulted in the call shape it has today. The issue here is that different libraries adhere to different call signatures (some even against the Node.js spec), making it rather problematic to ensure congruence on the interceptors' side.

**Comment by kettanaito** [comment]
Here's the issue I'm referring to above: https://github.com/mswjs/interceptors/issues/131 (https://github.com/mswjs/msw/issues/700). It was related to the `options.url` property being present, which is not a valid `RequestOptions` property. I think we've decided to go with `(url, options)` to support `https` client.

**Comment by kettanaito** [comment]
> I've managed to patch this issue for now by upgrading agent-base to version 6 via yarn resolutions as later versions don't monkey patch http.request

If the latest version of the library/dependencies functions properly, I'd not take any action. Using the latest versions of the tools is always a good idea.

**Comment by gerbyzation** [comment]
> I think we've decided to go with `(url, options)` to support `https` client.
Maybe I misunderstand but the https package supports both funciton signatures? 

Either way I agree this is a fine resolution as it's another (outdated) dependency partially implementing the signature from the standard library and occurrence doesn't seem that common. Thanks for taking a look @kettanaito

**Comment by kettanaito** [comment]
> Maybe I misunderstand but the https package supports both function signatures?

The native package does, but the third-party packages that may use it—no. This variability in the call signature bites in the back each time we see a report that LibraryX produces an error. Because LibraryX uses some strange combination of supported call signatures.
