### ISSUE TITLE
Attempted to log "TypeError: Cannot read property 'URL' of null

### ISSUE THREAD

**Issue by xyklex** [mswjs/interceptors#169]
Hi, hoping to get some help with the current issue

I'm trying to run a test to a React component that uses AWS Amplify, my tests are run with Jest with jsdom environment, and I'm using `msw`

When the test run I'm getting this output
```

  ●  Cannot log after tests are done. Did you forget to wait for something async in your test?
    Attempted to log "TypeError: Cannot read property 'URL' of null
        at new XMLHttpRequestImpl (/Users/metis/Directories/amplify/frontend/node_modules/jsdom/lib/jsdom/living/xhr/XMLHttpRequest-impl.js:111:32)
        at Object.exports.setup (/Users/metis/Directories/amplify/frontend/node_modules/jsdom/lib/jsdom/living/generated/XMLHttpRequest.js:62:12)
        at new XMLHttpRequest (/Users/metis/Directories/amplify/frontend/node_modules/jsdom/lib/jsdom/living/generated/XMLHttpRequest.js:101:22)
        at dispatchXhrRequest (/Users/metis/Directories/amplify/frontend/node_modules/axios/lib/adapters/xhr.js:21:19)
        at new Promise (<anonymous>)
        at xhrAdapter (/Users/metis/Directories/Users/metis/Directories/amplify/frontend/node_modules/axios/lib/core/dispatchRequest.js:52:10)
        at processTicksAndRejections (internal/process/task_queues.js:95:5)".

      336 |                           <Checkbox
      337 |                             checked={isItemSelected}
    > 338 |                             inputProps={{ 'aria-labelledby': labelId }}
          |               ^
      339 |                           />
      340 |                         </TableCell>
      341 |                         <TableCell

      at new XMLHttpRequestImpl (node_modules/jsdom/lib/jsdom/living/xhr/XMLHttpRequest-impl.js:111:32)
      at Object.exports.setup (node_modules/jsdom/lib/jsdom/living/generated/XMLHttpRequest.js:62:12)
      at new XMLHttpRequest (node_modules/jsdom/lib/jsdom/living/generated/XMLHttpRequest.js:101:22)
      at dispatchXhrRequest (node_modules/axios/lib/adapters/xhr.js:21:19)
      at xhrAdapter (node_modules/axios/lib/adapters/xhr.js:13:10)
      at dispatchRequest (node_modules/axios/lib/core/dispatchRequest.js:52:10)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)".
      at console.log (node_modules/@jest/console/build/CustomConsole.js:185:10)
      at retrieveDevices (src/Devices/Devices.js:338:15)
      at fetchData (src/Devices/Devices.js:320:9)

```

I tracked down the issue to the issue to be related to an object `_ownerDocument` being null. This issue is similar to this one https://github.com/mswjs/interceptors/issues/27

I have already spent some time trying to debug it but unfortunately can't find the solution, meanwhile, I'm sending the test data through props to the component to test it.

**Comment by xyklex** [comment]
Well, today with a fresh mind, I realized the issue was due to the async behavior, and by adding a `waitFor` element in my tests solved the issue.

**Comment by kettanaito** [comment]
Hey. I'm glad you got it resolved. Great job.

**Comment by shawn-p-m** [comment]
> Hi, hoping to get some help with the current issue
> 
> I'm trying to run a test to a React component that uses AWS Amplify, my tests are run with Jest with jsdom environment, and I'm using `msw`
> 
> When the test run I'm getting this output
> 
> ```
> 
>   ●  Cannot log after tests are done. Did you forget to wait for something async in your test?
>     Attempted to log "TypeError: Cannot read property 'URL' of null
>         at new XMLHttpRequestImpl (/Users/metis/Directories/amplify/frontend/node_modules/jsdom/lib/jsdom/living/xhr/XMLHttpRequest-impl.js:111:32)
>         at Object.exports.setup (/Users/metis/Directories/amplify/frontend/node_modules/jsdom/lib/jsdom/living/generated/XMLHttpRequest.js:62:12)
>         at new XMLHttpRequest (/Users/metis/Directories/amplify/frontend/node_modules/jsdom/lib/jsdom/living/generated/XMLHttpRequest.js:101:22)
>         at dispatchXhrRequest (/Users/metis/Directories/amplify/frontend/node_modules/axios/lib/adapters/xhr.js:21:19)
>         at new Promise (<anonymous>)
>         at xhrAdapter (/Users/metis/Directories/Users/metis/Directories/amplify/frontend/node_modules/axios/lib/core/dispatchRequest.js:52:10)
>         at processTicksAndRejections (internal/process/task_queues.js:95:5)".
> 
>       336 |                           <Checkbox
>       337 |                             checked={isItemSelected}
>     > 338 |                             inputProps={{ 'aria-labelledby': labelId }}
>           |               ^
>       339 |                           />
>       340 |                         </TableCell>
>       341 |                         <TableCell
> 
>       at new XMLHttpRequestImpl (node_modules/jsdom/lib/jsdom/living/xhr/XMLHttpRequest-impl.js:111:32)
>       at Object.exports.setup (node_modules/jsdom/lib/jsdom/living/generated/XMLHttpRequest.js:62:12)
>       at new XMLHttpRequest (node_modules/jsdom/lib/jsdom/living/generated/XMLHttpRequest.js:101:22)
>       at dispatchXhrRequest (node_modules/axios/lib/adapters/xhr.js:21:19)
>       at xhrAdapter (node_modules/axios/lib/adapters/xhr.js:13:10)
>       at dispatchRequest (node_modules/axios/lib/core/dispatchRequest.js:52:10)
>       at processTicksAndRejections (internal/process/task_queues.js:95:5)".
>       at console.log (node_modules/@jest/console/build/CustomConsole.js:185:10)
>       at retrieveDevices (src/Devices/Devices.js:338:15)
>       at fetchData (src/Devices/Devices.js:320:9)
> ```
> 
> I tracked down the issue to the issue to be related to an object `_ownerDocument` being null. This issue is similar to this one #27
> 
> I have already spent some time trying to debug it but unfortunately can't find the solution, meanwhile, I'm sending the test data through props to the component to test it.

I'm having this issue too. 

What msw and jest versions were you running?

**Comment by robmarshall** [comment]
Also just run into this issue

**Comment by 0xR** [comment]
I had the same issue. It was caused by the test finishing before the async call was made. This probably caused Jsdom to be cleaned up so that XMLHttpRequest does not work properly anymore.

I accidentally had a `getByText` where I needed a `findByText`. The latter will wait for async actions like the start of the XMLHttpRequest. The former just errors and exits the tests causing the confusing error message.
