### ISSUE TITLE
Unable to get data using https and mocked response

### ISSUE THREAD

**Issue by giuliopaci** [mswjs/interceptors#326]
I am trying to use this library to mock https requests, however I am not able to setup `@mswjs/interceptors` as I wanted.
In particular I would like to be able to mock response body and use the code that is tested below.

Unfortunately when `console.log(data)` is executed, for some reason `data` seems to be empty and `data` event is never triggered. On the other hand the `response.text()` is available in the intercepted response.

If I comment out `interceptor.apply();` the test seem to correctly work.

If I drop the interceptor request handler, i.e., if I delete this code:
```
interceptor.on('request', (request, requestId) => {
  request.respondWith(
    new Response('Hello', {
      status: 200,
      statusText: 'Ok',
      headers: { 'Content-Type': ['plain/text'] },
    })
  );
});
```
then I get an error since `res.complete` will not be `true` when the `end` event is triggered.

Am I doing something wrong or is it a bug?

```
import { BatchInterceptor } from '@mswjs/interceptors';
import nodeInterceptors from '@mswjs/interceptors/lib/presets/node';
import https from 'https';

const interceptor = new BatchInterceptor({
  name: 'hello',
  interceptors: nodeInterceptors,
});

interceptor.on('request', (request, requestId) => {
  request.respondWith(
    new Response('Hello', {
      status: 200,
      statusText: 'Ok',
      headers: { 'Content-Type': ['plain/text'] },
    })
  );
});

interceptor.on('response', (response, request) => {
  console.log(response.text());
});

beforeAll(async () => {
  interceptor.apply();
});

afterAll(async () => {
  interceptor.dispose();
});

test('Try MSW Interceptors', async () => {
  const req = new Promise((resolve, reject) => {
    https.get('https://en.wikipedia.org/wiki/Main_Page', { headers: { accept: 'application/json' } }, (res) => {
      let data = '';
      res.on('data', (chunk) => {
        data += chunk;
      });
      res.on('end', () => {
        if (res.complete) {
          console.log(data);
          resolve(res);
        } else {
          reject(res);
        }
      });
    });
  });
  await req.then((res) => {
    expect(res.statusCode).toBe(200);
  });
});
```

Current result:
```
  console.log
    Promise { 'Hello' }

      at src/app/App.test.jsx:3:27

  console.log


      at PassThrough.<anonymous> (src/app/App.test.jsx:39:3)

 PASS  src/app/App.test.jsx
  ✓ Try MSW Interceptors (26 ms)

----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
----------|---------|----------|---------|---------|-------------------
All files |       0 |        0 |       0 |       0 |                   
----------|---------|----------|---------|---------|-------------------
Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        0.769 s, estimated 1 s
```

**Comment by kettanaito** [comment]
This is likely fixed in the latest version of Interceptors. 

Since 0.32, we will emit the `response` event when receiving the first byte of the response, allowing you to read its body while the original client does the same. Our existing test cases for the response listener also pass. 

Let me know if you still encounter this issue after updating.
