### ISSUE TITLE
Error: cannot clone body after it is used with Remix V2

### ISSUE THREAD

**Issue by kettanaito** [mswjs/interceptors#402]
When running `remix dev` with this library, the following error is thrown:

```sh
Could not reach Remix dev server at http://localhost:3001/ping
Error: cannot clone body after it is used
    at clone (/node_modules/@remix-run/web-fetch/src/body.js:285:1)
    at new Request (/node_modules/@remix-run/web-fetch/src/request.js:100:1)
    at /node_modules/@remix-run/web-fetch/src/fetch.js:45:8
    at new Promise (<anonymous>)
    at AsyncFunction.fetch (/node_modules/@remix-run/web-fetch/src/fetch.js:43:9)
    at fetch (/node_modules/@remix-run/node/dist/fetch.js:27:19)
    at globalThis.fetch (/node_modules/@mswjs/interceptors/lib/node/interceptors/fetch/index.js:97:14)
    at Object.broadcastDevReady (/node_modules/@remix-run/server-runtime/dist/dev.js:20:18)
```

This originates from the heartbeat ping in Remix that is a `fetch` call with the following arguments:

```js
{
  input: 'http://localhost:3001/ping',
  init: {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: '{"buildHash":"1df2cab8"}'
  }
}
```

When we construct that into a `Request` representation for the interceptor, its `request.bodyUsed` is rightfully `false`. However, after some time, the value of `bodyUsed` becomes `true`. When we dispatch the request as usual, Remix's `web-fetch` throws on trying to clone a request with a used body.

https://github.com/mswjs/interceptors/blob/36400ccc47bf53b269888a7a3a5f452df592f58b/src/interceptors/fetch/index.ts#L99

> Us performing the intercepted request as-is.

https://github.com/remix-run/web-std-io/blob/5a3703c5c17523b9e8d39ad05eb58c3acc1734c3/packages/fetch/src/request.js#L98

> Remix checks if the request info is another request and its body exists, then proceeds to clone it.

https://github.com/remix-run/web-std-io/blob/5a3703c5c17523b9e8d39ad05eb58c3acc1734c3/packages/fetch/src/body.js#L282-L284

> Remix throws since `request.bodyUsed` is `true`.

**Comment by kettanaito** [comment]
A straightforward solution is to clone the request right after its construction. This will seal its `bodyUsed` and we will always provide a "clean" request to `pureFetch()`.

That doesn't explain how that request suddenly becomes read. Nothing on the Interceptor's side is reading it. Nothing on the consumer's side is reading it (no listeners/handlers). Remix cannot read it physically because it's never exposed to Remix (it's an internal intercepted request representation).

**Comment by kettanaito** [comment]
## Released: v0.24.0 🎉

This has been released in v0.24.0!

- 📄 [**Release notes**](https://github.com/mswjs/interceptors/releases/tag/v0.24.0)
- 📦 [npm package](https://www.npmjs.com/package/@mswjs/interceptors/v/0.24.0)

Make sure to always update to the latest version (`npm i @mswjs/interceptors@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.
