### ISSUE TITLE
caught (in promise) TypeError: Illegal invocation  

### ISSUE THREAD

**Issue by acheong08** [mswjs/interceptors#405]
```js
import { XMLHttpRequestInterceptor } from '@mswjs/interceptors/XMLHttpRequest';

const interceptor = new XMLHttpRequestInterceptor()

// Enable the interception of requests.
interceptor.apply()

// Listen to any "http.ClientRequest" being dispatched,
// and log its method and full URL.
interceptor.on('request', ({ request, requestId }) => {
  console.log(request.method, request.url)
})
```
```js
plugin:sample-plugin:3177 Uncaught TypeError: Illegal invocation
    at next (plugin:sample-plugin:3177:28)
    at Proxy.setProperty (plugin:sample-plugin:3256:20)
    at handler.set (plugin:sample-plugin:3188:26)
    at window.ajax (enhance.js:1:11991)
    at e.logout (app.js:1:264780)
    at app.js:1:2424502
    at HTMLButtonElement.<anonymous> (app.js:1:1324908)
```

Caught here:
```js
if (typeof (ownDescriptors == null ? void 0 : ownDescriptors.set) !== "undefined") {
        ownDescriptors.set.apply(target, [nextValue]);
        return
}
```
```js
nextValue.toString()
'function(){var t=p.status,e=p.response;t>=200&&t<400?r&&r(e,p):o&&o(e,p)}'
```
```js
target.toString()
'[object XMLHttpRequest]'
```

**Comment by acheong08** [comment]
Note: This is inside electron

**Comment by acheong08** [comment]
Solved. Seems to be a duplicate of #378
